name: Deploy

on:
  push:
    branches:
      - main # Ou sua branch de preferência

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no root@YOUR_DROPLET_IP "cd . && git pull origin main && npm install && npm run build && pm2 restart all"
