name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            eval `ssh-agent -s`
            ssh-add ~/.ssh/id_rsa
            rm -rf test
            mkdir test
            cd test
            git clone git@github.com:thecogmel/deploy-test.git
            echo 'Deployment to digital ocean finished'
