name: Continuos Integration

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: run install, build and test
        run: |
          npm install
          npm run build 
          npm run test